#
# To use, run:
#   docker build -t 5gen-c .
#   docker run -it 5gen-c /bin/bash
#

FROM ubuntu:16.04

RUN apt-get -y update
RUN apt-get -y install software-properties-common
RUN apt-get -y update
RUN apt-get -y install git
RUN apt-get -y install gcc g++
RUN apt-get -y install autoconf libtool make flex bison
RUN apt-get -y install libgmp-dev libmpfr-dev libssl-dev libflint-dev
RUN apt-get -y install python

#
# Get 5gen-c repository
#

WORKDIR /inst
RUN git clone https://github.com/5GenCrypto/5gen-c.git

WORKDIR /inst/5gen-c
RUN git pull origin master
RUN ./build.sh --no-cxs
